# Use root/example as user/password credentials
version: "3.1"

services:
  mysql:
    image: mysql:8.3.0
    container_name: isolation-levels-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3300:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password

  mysql-adminer:
    image: adminer:4.8.1
    container_name: isolation-levels-adminer
    restart: always
    ports:
      - "3400:8080"